FROM python:3.8.6


RUN apt-get -y update
RUN apt-get install -y postgresql

COPY app/ app/
COPY requirements.txt requirements.txt

RUN pip install --upgrade pip 
RUN pip install -r requirements.txt

RUN ls -la

CMD ["uvicorn", "app.main:create_app()", "--reload", "--host", "0.0.0.0", "--port", "80"]

